### ISSUE TITLE
Update to angular v.18

### ISSUE THREAD

**Issue by muhammadawaisshaikh** [naeem2290/pokemon#1]
Please update the code to v.18

**Comment by naeem2290** [comment]
@muhammadawaisshaikh There is no such requirement in the document that we need to develop it in v18. I have the setup of 16 currently so I used that.

**Comment by muhammadawaisshaikh** [comment]
Ok @naeem2290 this one is understandable but always consider the latest.

**Comment by muhammadawaisshaikh** [comment]
All commits should be well defined on deliverables of each small iteration. But you pushed all app in one go. That’s the concern here.
